version: '3'

services:
#   client:
#     build: ./client
#     ports:
#       - '3000:3000'
#     volumes:
#       - ./client:/usr/src/client

  api:
    build: ./api
    env_file: "./environments/.env.production"

    ports:
      - '4001:4001'
    # depends_on:
    #   - mongo
    volumes:
      - ./api/src:/usr/src/api/src

  # mongo:
  #   image: mongo:latest
  #   ports:
  #     - "27017:27017"
  #   volumes:
  #     - ./mongo-volume:/data/db