version: '3'

services:
  nginx:
    build:
      context: ./client
      dockerfile: Dockerfile
    env_file:
      - "./environments/.env.production"
    depends_on:
      - api
    restart: always
    ports:
      - "3000:80"


  api:
    build: ./api
    env_file: "./environments/.env.production"

    ports:
      - '4001:4001'
    volumes:
      - ./api/src:/usr/src/api/src