version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client:/node_modules

  api:
    build: ./api
    environment:
      - MONGODB_URL=mongodb://mongo:27017/produce-db
      - NODE_ENV=development
    ports:
      - '4001:4001'
    depends_on:
      - mongo
    volumes:
      - ./api/src:/usr/src/api/src

  mongo:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./mongo-volume:/data/db
