version: '3'

services:
  client:
    build: ./client
    ports:
      - '3000:3000'
    volumes:
      - ./client:/app
      - ./client:/node_modules
    networks:
      - node-network

  api:
    build: ./api
    environment:
      - MONGODB_URL=mongodb://mongodb:27017/
      - NODE_ENV=development
    ports:
      - '8000:8000'
    depends_on:
      - mongodb
    volumes:
      - ./api/src:/usr/src/api/src
    networks:
      - node-network

  mongodb:
    image: mongo
    ports:
      - '27017:27017'
    # volumes:
    #   - dbdata:/data/db
    networks:
      - node-network

# volumes:
#   dbdata:

networks:
  node-network:
    driver: bridge