#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

cd client

# build react app
npm run build

rm -rf ../api/src/dist

# Copy dist folder to api server
rsync -a dist ../api/src/dist

# delete dist folder from client
rm -rf dist